include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - '**/l10n/*.dart'
    - '**/*.freezed.dart'
    - '**/*.g.dart'

linter:
  rules:
    sort_pub_dependencies: false
    use_build_context_synchronously: false
