name: dating_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  go_router: ^4.2.2
  flutter_riverpod: ^2.0.0-dev.9
  gap: ^2.0.0
  carousel_slider: ^4.1.1
  flutter_svg: ^1.1.1+1
  smooth_page_indicator: ^1.0.0+2
  device_preview: ^1.1.0
  adaptive_dialog: ^1.8.0
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  simple_logger: ^1.9.0
  permission_handler: ^10.0.0
  collection: ^1.16.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  cloud_firestore: ^3.4.5
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  pin_code_fields: ^7.4.0
  package_info_plus: ^1.4.3+1
  firebase_storage: ^10.3.7
  cached_network_image: ^3.2.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.19.2
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.1.6
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  test: ^1.21.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/sign_up/
    - assets/images/setup/setup_photo/
    - assets/images/setup/setup_complete/
    - assets/images/profile/
